version: '2.4'
services:
    redis:
        container_name: redis
        image: redis:alpine
        restart: 'no'
        ports:
            - '8287:8287'
        command: redis-server --port 8287 --requirepass redis
