name: Improved Type Gen

on:
  push:
    branches:
      - ci/improve-type-gen

jobs:
  ImprovedTypeGen:
    name: Improved Type Gen test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      saelem:
        image: ghcr.io/skyra-project/saelem:latest
        env:
          SAELEM_REDIS_HOST: redis
          SAELEM_REDIS_PORT: 6379
          SAELEM_REDIS_PASSWORD: "''"
          SAELEM_REDIS_DATABASE: 0
        options: >-
          --health-cmd "nc -z localhost 8284"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 6
          --health-start-period 5s
        ports:
          - 8284:8284
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile
      - name: Generate GraphQL Schema code
        run: yarn codegen
      - name: Upload typescript bundle to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: typescript_bundle
          path: generated/ts/
          if-no-files-found: error
